# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - quatroEmLinha

on:
  push:
    branches:
      - server
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_5762f05336924f6c8b2e55585baf00a7 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a88d7c6a6f94421f8eeec1c3838f9fd0 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_5762f05336924f6c8b2e55585baf00a7 }}/danielschei/quatro-em-linha-frontend-server:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'quatroEmLinha'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_79bc48976ae141909c86145e3a62bd1e }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_5762f05336924f6c8b2e55585baf00a7 }}/danielschei/quatro-em-linha-frontend-server:${{ github.sha }}'